
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Windows - 10.0.26100 - AMD64
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CheckCCompilerFlag.cmake:51 (cmake_check_compiler_flag)"
      - "build-web/_deps/raylib-src/cmake/AddIfFlagCompiles.cmake:3 (CHECK_C_COMPILER_FLAG)"
      - "build-web/_deps/raylib-src/cmake/CompilerFlags.cmake:5 (add_if_flag_compiles)"
      - "build-web/_deps/raylib-src/CMakeLists.txt:29 (include)"
    checks:
      - "Performing Test COMPILER_HAS_THOSE_TOGGLES"
    directories:
      source: "C:/Users/Frost/Code/RaylibTest/build-web/CMakeFiles/CMakeScratch/TryCompile-99i686"
      binary: "C:/Users/Frost/Code/RaylibTest/build-web/CMakeFiles/CMakeScratch/TryCompile-99i686"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "C:/Users/Frost/Code/emsdk/upstream/emscripten/emscan-deps"
      CMAKE_C_FLAGS: ""
      CMAKE_MODULE_PATH: "C:/Users/Frost/Code/RaylibTest/build-web/_deps/raylib-src/cmake"
    buildResult:
      variable: "COMPILER_HAS_THOSE_TOGGLES"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Frost/Code/RaylibTest/build-web/CMakeFiles/CMakeScratch/TryCompile-99i686'
        
        Run Build Command(s): C:/PROGRA~1/CMake/bin/ninja.exe -v cmTC_2a796
        [1/2] C:\\Users\\Frost\\Code\\emsdk\\upstream\\emscripten\\emcc.bat -DCOMPILER_HAS_THOSE_TOGGLES  -Werror=pointer-arith -MD -MT CMakeFiles/cmTC_2a796.dir/src.c.o -MF CMakeFiles\\cmTC_2a796.dir\\src.c.o.d -o CMakeFiles/cmTC_2a796.dir/src.c.o -c C:/Users/Frost/Code/RaylibTest/build-web/CMakeFiles/CMakeScratch/TryCompile-99i686/src.c
        [2/2] C:\\WINDOWS\\system32\\cmd.exe /C "cd . && C:\\Users\\Frost\\Code\\emsdk\\upstream\\emscripten\\emcc.bat   CMakeFiles/cmTC_2a796.dir/src.c.o -o cmTC_2a796.js   && cd ."
        
      exitCode: 0
...
