var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type;let da;(da=h).expectedDataFileDownloads??(da.expectedDataFileDownloads=0);h.expectedDataFileDownloads++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;if(!("undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a)){var b="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;(function(c){function d(p,r,v,C){if(b)require("fs").readFile(p,(w,G)=>{w?C(w):v(G.buffer)});else{var D;(D=h).dataFileDownloads??(D.dataFileDownloads={});fetch(p).catch(w=>Promise.reject(Error(`Network Error: ${p}`,{cause:w}))).then(w=>
{if(!w.ok)return Promise.reject(Error(`${w.status}: ${w.url}`));if(!w.body&&w.arrayBuffer)return w.arrayBuffer().then(v);const G=w.body.getReader(),P=()=>G.read().then(Kf).catch(V=>Promise.reject(Error(`Unexpected error while handling : ${w.url} ${V}`,{cause:V}))),O=[],Jb=Number(w.headers.get("Content-Length")??r);let K=0;const Kf=({done:V,value:Dc})=>{if(V){var Ma=new Uint8Array(O.map(Kb=>Kb.length).reduce((Kb,Lf)=>Kb+Lf,0));V=0;for(var Na of O)Ma.set(Na,V),V+=Na.length;v(Ma.buffer)}else{O.push(Dc);
K+=Dc.length;h.dataFileDownloads[p]={loaded:K,total:Jb};V=Na=0;for(Ma of Object.values(h.dataFileDownloads))Na+=Ma.loaded,V+=Ma.total;h.setStatus?.(`Downloading data... (${Na}/${V})`);return P()}};h.setStatus?.("Downloading data...");return P()})}}function e(p){console.error("package error:",p)}function f(p){function r(w,G,P){this.start=w;this.end=G;this.audio=P}function v(w){if(!w)throw"Loading data file failed."+Error().stack;if(w.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+
Error().stack;w=new Uint8Array(w);r.prototype.df=w;w=c.files;for(var G=0;G<w.length;++G)r.prototype.Me[w[G].filename].onload();p.removeRunDependency("datafile_RaylibTest.data")}p.FS_createPath("/","assets",!0,!0);r.prototype={Me:{},open:function(w,G){this.name=G;this.Me[G]=this;p.addRunDependency(`fp ${this.name}`)},send:function(){},onload:function(){this.finish(this.df.subarray(this.start,this.end))},finish:function(w){p.FS_createDataFile(this.name,null,w,!0,!0,!0);p.removeRunDependency(`fp ${this.name}`);
this.Me[this.name]=null}};for(var C=c.files,D=0;D<C.length;++D)(new r(C[D].start,C[D].end,C[D].audio||0)).open("GET",C[D].filename);p.addRunDependency("datafile_RaylibTest.data");p.preloadResults??(p.preloadResults={});p.preloadResults["RaylibTest.data"]={ih:!1};t?(v(t),t=null):q=v}"object"===typeof window?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.substring(0,
location.pathname.lastIndexOf("/"))+"/");var g=h.locateFile?h.locateFile("RaylibTest.data",""):"RaylibTest.data",l=c.remote_package_size,q=null,t=h.getPreloadedPackage?h.getPreloadedPackage(g,l):null;t||d(g,l,p=>{q?(q(p),q=null):t=p},e);if(h.calledRun)f(h);else{let p;((p=h).preRun??(p.preRun=[])).push(f)}})({files:[{filename:"/assets/cube.obj",start:0,end:919},{filename:"/assets/ocean.obj",start:919,end:331701},{filename:"/assets/test.obj",start:331701,end:394724},{filename:"/assets/test_2.mtl",start:394724,
end:394775},{filename:"/assets/test_2.obj",start:394775,end:679563},{filename:"/assets/test_2_smooth.mtl",start:679563,end:679614},{filename:"/assets/test_2_smooth.obj",start:679614,end:965667},{filename:"/assets/test_3.mtl",start:965667,end:965718},{filename:"/assets/test_3.obj",start:965718,end:2093230},{filename:"/assets/test_old.obj",start:2093230,end:2134474},{filename:"/assets/test_smooth.mtl",start:2134474,end:2134525},{filename:"/assets/test_smooth.obj",start:2134525,end:2197750}],remote_package_size:2197750})}})();
var ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),na,m=!1,oa,la=a=>a.startsWith("file://"),pa,n,u,qa,ra,x,y,z,sa,ta;
function ua(){var a=pa.buffer;n=new Int8Array(a);qa=new Int16Array(a);u=new Uint8Array(a);ra=new Uint16Array(a);x=new Int32Array(a);y=new Uint32Array(a);z=new Float32Array(a);sa=new Float64Array(a);ta=new BigInt64Array(a);new BigUint64Array(a)}var va=0,wa=null;function xa(){va++;h.monitorRunDependencies?.(va)}function ya(){va--;h.monitorRunDependencies?.(va);if(0==va&&wa){var a=wa;wa=null;a()}}
function za(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);m=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Aa;async function Ba(a){if(!na)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==Aa&&na)a=new Uint8Array(na);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Ca(a,b){try{var c=await Ba(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),za(d)}}async function Da(a){var b=Aa;if(!na&&"function"==typeof WebAssembly.instantiateStreaming&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return Ca(b,a)}
class Ea{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Fa=a=>{for(;0<a.length;)a.shift()(h)},Ga=[],Ha=[],Ia=()=>{var a=h.preRun.shift();Ha.push(a)},Ja=!0,Ka="undefined"!=typeof TextDecoder?new TextDecoder:void 0,A=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ka)return Ka.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=
65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d};class La{constructor(a){this.Af=a-24}}
var Oa=0,Pa=0,Qa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ra=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Qa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Sa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Ta=()=>{if(ca){var a=
require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Ua=a=>{(Ua=Ta())(a)},Va=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Qa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Wa=[],Xa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):
b+=3}return b},B=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Ya=a=>{var b=Array(Xa(a)+1);a=B(a,b,0,b.length);b.length=a;return b},Za=[];
function $a(a,b){Za[a]={input:[],output:[],Ye:b};ab(a,bb)}
var bb={open(a){var b=Za[a.node.rdev];if(!b)throw new E(43);a.tty=b;a.seekable=!1},close(a){a.tty.Ye.fsync(a.tty)},fsync(a){a.tty.Ye.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Ye.fg)throw new E(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Ye.fg(a.tty)}catch(l){throw new E(29);}if(void 0===g&&0===e)throw new E(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Ye.Qf)throw new E(60);try{for(var e=0;e<d;e++)a.tty.Ye.Qf(a.tty,b[c+e])}catch(f){throw new E(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},cb={fg(){a:{if(!Wa.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Wa=Ya(a)}a=Wa.shift()}return a},Qf(a,b){null===b||10===b?(ma(A(a.output)),a.output=[]):0!=
b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ma(A(a.output)),a.output=[])},Cg(){return{Wg:25856,Yg:5,Vg:191,Xg:35387,Ug:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Dg(){return 0},Eg(){return[24,80]}},db={Qf(a,b){null===b||10===b?(k(A(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(k(A(a.output)),a.output=[])}},F={Se:null,Xe(){return F.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new E(63);
F.Se||(F.Se={dir:{node:{$e:F.Ke.$e,Te:F.Ke.Te,lookup:F.Ke.lookup,xf:F.Ke.xf,rename:F.Ke.rename,unlink:F.Ke.unlink,rmdir:F.Ke.rmdir,readdir:F.Ke.readdir,symlink:F.Ke.symlink},stream:{Qe:F.Je.Qe}},file:{node:{$e:F.Ke.$e,Te:F.Ke.Te},stream:{Qe:F.Je.Qe,read:F.Je.read,write:F.Je.write,Pf:F.Je.Pf,jg:F.Je.jg}},link:{node:{$e:F.Ke.$e,Te:F.Ke.Te,readlink:F.Ke.readlink},stream:{}},bg:{node:{$e:F.Ke.$e,Te:F.Ke.Te},stream:eb}});c=fb(a,b,c,d);H(c.mode)?(c.Ke=F.Se.dir.node,c.Je=F.Se.dir.stream,c.Ge={}):32768===
(c.mode&61440)?(c.Ke=F.Se.file.node,c.Je=F.Se.file.stream,c.Le=0,c.Ge=null):40960===(c.mode&61440)?(c.Ke=F.Se.link.node,c.Je=F.Se.link.stream):8192===(c.mode&61440)&&(c.Ke=F.Se.bg.node,c.Je=F.Se.bg.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.Ge[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},kh(a){return a.Ge?a.Ge.subarray?a.Ge.subarray(0,a.Le):new Uint8Array(a.Ge):new Uint8Array(0)},Ke:{$e(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=
a.rdev;H(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Le:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Te(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Le!=b&&(0==b?(a.Ge=null,a.Le=0):(c=a.Ge,a.Ge=new Uint8Array(b),c&&a.Ge.set(c.subarray(0,Math.min(b,a.Le))),a.Le=b)))},lookup(){throw F.cg;
},xf(a,b,c,d){return F.createNode(a,b,c,d)},rename(a,b,c){try{var d=gb(b,c)}catch(f){}if(d){if(H(a.mode))for(var e in d.Ge)throw new E(55);hb(d)}delete a.parent.Ge[a.name];b.Ge[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.Ge[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=gb(a,b),d;for(d in c.Ge)throw new E(55);delete a.Ge[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.Ge)]},symlink(a,b,c){a=F.createNode(a,b,41471,0);a.link=
c;return a},readlink(a){if(40960!==(a.mode&61440))throw new E(28);return a.link}},Je:{read(a,b,c,d,e){var f=a.node.Ge;if(e>=a.node.Le)return 0;a=Math.min(a.node.Le-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===n.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.Ge||a.Ge.subarray)){if(f)return a.Ge=b.subarray(c,c+d),a.Le=d;if(0===a.Le&&0===e)return a.Ge=b.slice(c,c+d),a.Le=d;if(e+d<=a.Le)return a.Ge.set(b.subarray(c,
c+d),e),d}f=e+d;var g=a.Ge?a.Ge.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.Ge,a.Ge=new Uint8Array(f),0<a.Le&&a.Ge.set(g.subarray(0,a.Le),0));if(a.Ge.subarray&&b.subarray)a.Ge.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Ge[e+f]=b[c+f];a.Le=Math.max(a.Le,e+d);return d},Qe(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Le);if(0>b)throw new E(28);return b},Pf(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new E(43);a=a.node.Ge;
if(e&2||!a||a.buffer!==n.buffer){d=!0;za();e=void 0;if(!e)throw new E(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);n.set(a,e)}}else d=!1,e=a.byteOffset;return{Af:e,Pg:d}},jg(a,b,c,d){F.Je.write(a,b,0,d,c,!1);return 0}}},ib=async a=>{a=await ja(a);return new Uint8Array(a)},jb=[],mb=(a,b,c,d)=>{"undefined"!=typeof kb&&lb();var e=!1;jb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},nb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);
return c},ob=null,pb={},qb=[],rb=1,sb=null,tb=!1,ub=!0,vb={},E=class{name="ErrnoError";constructor(a){this.Ne=a}},wb=class{Me={};node=null;get flags(){return this.Me.flags}set flags(a){this.Me.flags=a}get position(){return this.Me.position}set position(a){this.Me.position=a}},xb=class{Ke={};Je={};jf=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Xe=a.Xe;this.id=rb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?
this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Gg(){return H(this.mode)}get Fg(){return 8192===(this.mode&61440)}};
function yb(a,b={}){if(!a)throw new E(44);b.Hf??(b.Hf=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(l=>!!l);for(var d=ob,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Sa(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");continue a}else d=d.parent;else{e=Ra(e+"/"+a[f]);try{d=gb(d,a[f])}catch(l){if(44===l?.Ne&&g&&b.Jg)return{path:e};throw l;}!d.jf||g&&!b.Hf||(d=d.jf.root);if(40960===(d.mode&61440)&&(!g||b.qf)){if(!d.Ke.readlink)throw new E(52);
d=d.Ke.readlink(d);"/"===d.charAt(0)||(d=Sa(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new E(32);}function zb(a){for(var b;;){if(a===a.parent)return a=a.Xe.ig,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Ab(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%sb.length}
function hb(a){var b=Ab(a.parent.id,a.name);if(sb[b]===a)sb[b]=a.bf;else for(b=sb[b];b;){if(b.bf===a){b.bf=a.bf;break}b=b.bf}}function gb(a,b){var c=H(a.mode)?(c=Bb(a,"x"))?c:a.Ke.lookup?0:2:54;if(c)throw new E(c);for(c=sb[Ab(a.id,b)];c;c=c.bf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ke.lookup(a,b)}function fb(a,b,c,d){a=new xb(a,b,c,d);b=Ab(a.parent.id,a.name);a.bf=sb[b];return sb[b]=a}function H(a){return 16384===(a&61440)}
function Cb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Bb(a,b){if(ub)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Db(a,b){if(!H(a.mode))return 54;try{return gb(a,b),20}catch(c){}return Bb(a,"wx")}function Eb(a){a=qb[a];if(!a)throw new E(8);return a}
function Fb(a,b=-1){a=Object.assign(new wb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!qb[b])break a;throw new E(33);}a.fd=b;return qb[b]=a}function Gb(a,b=-1){a=Fb(a,b);a.Je?.fh?.(a);return a}function Hb(a,b){var c=null?.Je.Te,d=c?null:a;c??=a.Ke.Te;if(!c)throw new E(63);c(d,b)}var eb={open(a){a.Je=pb[a.node.rdev].Je;a.Je.open?.(a)},Qe(){throw new E(70);}};function ab(a,b){pb[a]={Je:b}}
function Ib(a,b){var c="/"===b;if(c&&ob)throw new E(10);if(!c&&b){var d=yb(b,{Hf:!1});b=d.path;d=d.node;if(d.jf)throw new E(10);if(!H(d.mode))throw new E(54);}b={type:a,oh:{},ig:b,Ig:[]};a=a.Xe(b);a.Xe=b;b.root=a;c?ob=a:d&&(d.jf=b,d.Xe&&d.Xe.Ig.push(b))}function Lb(a,b,c){var d=yb(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new E(28);if("."===a||".."===a)throw new E(20);var e=Db(d,a);if(e)throw new E(e);if(!d.Ke.xf)throw new E(63);return d.Ke.xf(d,a,b,c)}
function Mb(a,b=438){return Lb(a,b&4095|32768,0)}function I(a){return Lb(a,16895,0)}function Nb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Lb(a,b|8192,c)}function Ob(a,b){if(!Va(a))throw new E(44);var c=yb(b,{parent:!0}).node;if(!c)throw new E(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=Db(c,b);if(d)throw new E(d);if(!c.Ke.symlink)throw new E(63);c.Ke.symlink(c,b,a)}
function Pb(a){var b=yb(a,{parent:!0}).node;if(!b)throw new E(44);a=a&&a.match(/([^\/]+|\/)\/*$/)[1];var c=gb(b,a);a:{try{var d=gb(b,a)}catch(f){d=f.Ne;break a}var e=Bb(b,"wx");d=e?e:H(d.mode)?31:0}if(d)throw new E(d);if(!b.Ke.unlink)throw new E(63);if(c.jf)throw new E(10);b.Ke.unlink(b,a);hb(c)}function Qb(a,b){a="string"==typeof a?yb(a,{qf:!0}).node:a;Hb(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),eh:void 0})}
function Rb(a,b,c=438){if(""===a)throw new E(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=yb(a,{qf:!(b&131072),Jg:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new E(20);}else{if(e)throw new E(31);d=Lb(a,c|511,0);f=!0}if(!d)throw new E(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!H(d.mode))throw new E(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:H(d.mode)&&("r"!==Cb(b)||b&576)?31:Bb(d,Cb(b)):44))throw new E(e);if(b&512&&!f){e=d;e="string"==typeof e?yb(e,{qf:!0}).node:e;if(H(e.mode))throw new E(31);if(32768!==(e.mode&61440))throw new E(28);var g=Bb(e,"w");if(g)throw new E(g);Hb(e,{size:0,timestamp:Date.now()})}b&=-131713;e=Fb({node:d,path:zb(d),flags:b,seekable:!0,position:0,Je:d.Je,Mg:[],error:!1});e.Je.open&&e.Je.open(e);f&&Qb(d,c&511);!h.logReadFiles||b&1||a in vb||(vb[a]=1);return e}
function Sb(a){if(null===a.fd)throw new E(8);a.Mf&&(a.Mf=null);try{a.Je.close&&a.Je.close(a)}catch(b){throw b;}finally{qb[a.fd]=null}a.fd=null}function Tb(a,b,c){if(null===a.fd)throw new E(8);if(!a.seekable||!a.Je.Qe)throw new E(70);if(0!=c&&1!=c&&2!=c)throw new E(28);a.position=a.Je.Qe(a,b,c);a.Mg=[]}
function Ub(a,b,c,d,e,f){if(0>d||0>e)throw new E(28);if(null===a.fd)throw new E(8);if(0===(a.flags&2097155))throw new E(8);if(H(a.node.mode))throw new E(31);if(!a.Je.write)throw new E(28);a.seekable&&a.flags&1024&&Tb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new E(70);b=a.Je.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Vb(a,b){a="string"==typeof a?a:zb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ra(a+"/"+c);try{I(d)}catch(e){if(20!=e.Ne)throw e;}a=d}}return d}function Wb(a,b,c,d){a=Ra(("string"==typeof a?a:zb(a))+"/"+b);return Mb(a,nb(c,d))}
function Xb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:zb(a),g=b?Ra(a+"/"+b):a);a=nb(d,e);g=Mb(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Qb(g,a|146);b=Rb(g,577);Ub(b,c,0,c.length,0,f);Sb(b);Qb(g,a)}}
function Yb(a,b,c,d){a=Ra(("string"==typeof a?a:zb(a))+"/"+b);b=nb(!!c,!!d);Yb.hg??(Yb.hg=64);var e=Yb.hg++<<8|0;ab(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,l,q){for(var t=0,p=0;p<q;p++){try{var r=c()}catch(v){throw new E(29);}if(void 0===r&&0===t)throw new E(6);if(null===r||void 0===r)break;t++;g[l+p]=r}t&&(f.node.atime=Date.now());return t},write(f,g,l,q){for(var t=0;t<q;t++)try{d(g[l+t])}catch(p){throw new E(29);}q&&(f.node.mtime=f.node.ctime=Date.now());return t}});
return Nb(a,b,e)}function Zb(a){if(!(a.Fg||a.Gg||a.link||a.Ge)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.Ge=ka(a.url),a.Le=a.Ge.length}catch(b){throw new E(29);}}}
function $b(a,b,c,d,e){class f{Ef=!1;Me=[];df=void 0;Zf=0;Yf=0;get(p){if(!(p>this.length-1||0>p)){var r=p%this.chunkSize;return this.df(p/this.chunkSize|0)[r]}}ug(p){this.df=p}$f(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var r=Number(p.getResponseHeader("Content-length")),v,C=(v=p.getResponseHeader("Accept-Ranges"))&&"bytes"===v;p=(v=p.getResponseHeader("Content-Encoding"))&&"gzip"===
v;var D=1048576;C||(D=r);var w=this;w.ug(G=>{var P=G*D,O=(G+1)*D-1;O=Math.min(O,r-1);if("undefined"==typeof w.Me[G]){var Jb=w.Me;if(P>O)throw Error("invalid range ("+P+", "+O+") or no bytes requested!");if(O>r-1)throw Error("only "+r+" bytes available! programmer error!");var K=new XMLHttpRequest;K.open("GET",c,!1);r!==D&&K.setRequestHeader("Range","bytes="+P+"-"+O);K.responseType="arraybuffer";K.overrideMimeType&&K.overrideMimeType("text/plain; charset=x-user-defined");K.send(null);if(!(200<=K.status&&
300>K.status||304===K.status))throw Error("Couldn't load "+c+". Status: "+K.status);P=void 0!==K.response?new Uint8Array(K.response||[]):Ya(K.responseText||"");Jb[G]=P}if("undefined"==typeof w.Me[G])throw Error("doXHR failed!");return w.Me[G]});if(p||!r)D=r=1,D=r=this.df(0).length,ma("LazyFiles on gzip forces download of the whole file when length is accessed");this.Zf=r;this.Yf=D;this.Ef=!0}get length(){this.Ef||this.$f();return this.Zf}get chunkSize(){this.Ef||this.$f();return this.Yf}}if("undefined"!=
typeof XMLHttpRequest){if(!ba)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var g=new f;var l=void 0}else l=c,g=void 0;var q=Wb(a,b,d,e);g?q.Ge=g:l&&(q.Ge=null,q.url=l);Object.defineProperties(q,{Le:{get:function(){return this.Ge.length}}});var t={};Object.keys(q.Je).forEach(p=>{var r=q.Je[p];t[p]=(...v)=>{Zb(q);return r(...v)}});t.read=(p,r,v,C,D)=>{Zb(q);p=p.node.Ge;if(D>=p.length)r=0;else{C=Math.min(p.length-D,C);if(p.slice)for(var w=
0;w<C;w++)r[v+w]=p[D+w];else for(w=0;w<C;w++)r[v+w]=p.get(D+w);r=C}return r};t.Pf=()=>{Zb(q);za();throw new E(48);};q.Je=t;return q}var ac={};function bc(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":Eb(a).path;if(0==b.length)throw new E(44);return a+"/"+b}
var cc=void 0,dc=()=>{var a=x[+cc>>2];cc+=4;return a},ec=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],fc=a=>{a=2<a?a?A(u,a):"":a;return ec[a]||("undefined"!=typeof document?document.querySelector(a):null)},gc=a=>0>ec.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};function hc(a){var b=J.Oe[a];b.target.removeEventListener(b.We,b.dg,b.cf);J.Oe.splice(a,1)}
function ic(){if(navigator.userActivation?navigator.userActivation.isActive:J.Of&&J.vg.Ff){var a=J.Ze;J.Ze=[];for(var b of a)b.Tf(...b.ag)}}function jc(a){if(!a.target)return-4;if(a.ef)a.dg=function(c){++J.Of;J.vg=a;ic();a.hf(c);ic();--J.Of},a.target.addEventListener(a.We,a.dg,a.cf),J.Oe.push(a);else for(var b=0;b<J.Oe.length;++b)J.Oe[b].target==a.target&&J.Oe[b].We==a.We&&hc(b--);return 0}
var J={Sg:0,Lf:0,lh:0,zf:0,xh:0,Vf:0,hh:0,dh:0,ph:0,bh:0,Kf:0,qh:0,wh:0,Uf:0,mh(a,b,c){n.set(n.subarray(b,b+c),a)},rh(){for(;J.Oe.length;)hc(J.Oe.length-1);J.Ze=[]},Of:0,Ze:[],ah(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l in f)if(f[l]!=g[l])return!1;return!0}for(var e of J.Ze)if(e.Tf==a&&d(e.ag,c))return;J.Ze.push({Tf:a,lg:b,ag:c});J.Ze.sort((f,g)=>f.lg<g.lg)},th(a){J.Ze=J.Ze.filter(b=>b.Tf!=a)},Oe:[],sh:(a,b)=>{for(var c=0;c<J.Oe.length;++c)J.Oe[c].target!=a||b&&b!=J.Oe[c].We||
hc(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},kc=(a,b)=>{sa[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)sa[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)sa[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)n[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];n[a+1104]=b.connected;x[a+1108>>2]=b.index;x[a+8>>2]=b.axes.length;x[a+12>>2]=b.buttons.length;
B(b.id,u,a+1112,64);B(b.mapping,u,a+1176,64)},L,lc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},mc=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),
a.isVertexArray=c=>b.isVertexArrayOES(c))},nc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},oc=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},pc=1,qc=[],M=[],rc=[],sc=[],tc=[],N=[],uc=[],vc=[],wc=[],xc={},yc=4,zc=0,Ac=a=>{for(var b=pc++,c=a.length;c<b;c++)a[c]=null;return b},Bc=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=L[c](),g=f&&Ac(d);f?(f.name=g,d[g]=f):Q||=1282;x[b+4*e>>2]=g}},Ec=(a,b)=>{a.Me||(a.Me=a.getContext,a.getContext=function(d,e){e=a.Me(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Cc(c,b):0},Cc=(a,b)=>
{var c=Ac(vc),d={handle:c,attributes:b,version:b.Hg,Df:a};a.canvas&&(a.canvas.Og=d);vc[c]=d;("undefined"==typeof b.xg||b.xg)&&Fc(d);return c},Fc=a=>{a||=Gc;if(!a.Ag){a.Ag=!0;var b=a.Df;b.nh=b.getExtension("WEBGL_multi_draw");b.zg=b.getExtension("EXT_polygon_offset_clamp");b.yg=b.getExtension("EXT_clip_control");b.Ng=b.getExtension("WEBGL_polygon_mode");lc(b);mc(b);nc(b);b.Ue=b.getExtension("EXT_disjoint_timer_query");oc(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},
Hc={},Q,Gc,Ic=a=>L.activeTexture(a),Jc=(a,b)=>{L.attachShader(M[a],N[b])},Kc=(a,b,c)=>{L.bindAttribLocation(M[a],b,c?A(u,c):"")},Lc=(a,b)=>{L.bindBuffer(a,qc[b])},Mc=(a,b)=>{L.bindFramebuffer(a,rc[b])},Nc=(a,b)=>{L.bindRenderbuffer(a,sc[b])},Oc=(a,b)=>{L.bindTexture(a,tc[b])},Pc=(a,b)=>L.blendFunc(a,b),Qc=(a,b,c,d)=>{L.bufferData(a,c?u.subarray(c,c+b):b,d)},Rc=(a,b,c,d)=>{L.bufferSubData(a,b,u.subarray(d,d+c))},Sc=a=>L.checkFramebufferStatus(a),Tc=a=>L.clear(a),Uc=(a,b,c,d)=>L.clearColor(a,b,c,d),
Vc=a=>L.clearDepth(a),Wc=a=>{L.compileShader(N[a])},Xc=(a,b,c,d,e,f,g,l)=>{L.compressedTexImage2D(a,b,c,d,e,f,u.subarray(l,l+g))},Yc=()=>{var a=Ac(M),b=L.createProgram();b.name=a;b.wf=b.uf=b.vf=0;b.Wf=1;M[a]=b;return a},Zc=a=>{var b=Ac(N);N[b]=L.createShader(a);return b},$c=a=>L.cullFace(a),ad=(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=qc[d];e&&(L.deleteBuffer(e),e.name=0,qc[d]=null)}},bd=(a,b)=>{for(var c=0;c<a;++c){var d=x[b+4*c>>2],e=rc[d];e&&(L.deleteFramebuffer(e),e.name=0,rc[d]=null)}},
cd=a=>{if(a){var b=M[a];b?(L.deleteProgram(b),b.name=0,M[a]=null):Q||=1281}},dd=(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=sc[d];e&&(L.deleteRenderbuffer(e),e.name=0,sc[d]=null)}},ed=a=>{if(a){var b=N[a];b?(L.deleteShader(b),N[a]=null):Q||=1281}},fd=(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=tc[d];e&&(L.deleteTexture(e),e.name=0,tc[d]=null)}},gd=a=>L.depthFunc(a),hd=(a,b)=>{L.detachShader(M[a],N[b])},jd=a=>L.disable(a),kd=a=>{L.disableVertexAttribArray(a)},ld=(a,b,c)=>{L.drawArrays(a,
b,c)},md=[],nd=(a,b,c,d)=>{L.drawElements(a,b,c,d)},od=a=>L.enable(a),pd=a=>{L.enableVertexAttribArray(a)},qd=(a,b,c,d)=>{L.framebufferRenderbuffer(a,b,c,sc[d])},rd=(a,b,c,d,e)=>{L.framebufferTexture2D(a,b,c,tc[d],e)},sd=a=>L.frontFace(a),td=(a,b)=>{Bc(a,b,"createBuffer",qc)},ud=(a,b)=>{Bc(a,b,"createFramebuffer",rc)},vd=(a,b)=>{Bc(a,b,"createRenderbuffer",sc)},wd=(a,b)=>{Bc(a,b,"createTexture",tc)},xd=(a,b,c,d,e,f,g,l)=>{b=M[b];if(a=L[a](b,c))d=l&&B(a.name,u,l,d),e&&(x[e>>2]=d),f&&(x[f>>2]=a.size),
g&&(x[g>>2]=a.type)},yd=(a,b)=>L.getAttribLocation(M[a],b?A(u,b):""),zd=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(Q||=1280);return;case 36345:d=0;break;case 34466:var e=L.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=L.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":Q||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=
0;break;default:Q||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:x[b+4*a>>2]=e[a];break;case 2:z[b+4*a>>2]=e[a];break;case 4:n[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){Q||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:Q||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:c=d;y[b>>2]=c;y[b+4>>2]=(c-y[b>>2])/4294967296;break;case 0:x[b>>2]=d;break;case 2:z[b>>2]=d;break;case 4:n[b]=d?1:0}}else Q||=1281},Ad=(a,b)=>zd(a,b,2),Bd=(a,b,c,d)=>{a=L.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;x[d>>2]=a},Cd=(a,b,c,d)=>{a=L.getProgramInfoLog(M[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,u,d,b):0;c&&(x[c>>2]=b)},Dd=(a,b,c)=>{if(c)if(a>=pc)Q||=1281;else if(a=M[a],35716==b)a=L.getProgramInfoLog(a),
null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b){if(!a.wf){var d=L.getProgramParameter(a,35718);for(b=0;b<d;++b)a.wf=Math.max(a.wf,L.getActiveUniform(a,b).name.length+1)}x[c>>2]=a.wf}else if(35722==b){if(!a.uf)for(d=L.getProgramParameter(a,35721),b=0;b<d;++b)a.uf=Math.max(a.uf,L.getActiveAttrib(a,b).name.length+1);x[c>>2]=a.uf}else if(35381==b){if(!a.vf)for(d=L.getProgramParameter(a,35382),b=0;b<d;++b)a.vf=Math.max(a.vf,L.getActiveUniformBlockName(a,b).length+1);x[c>>2]=a.vf}else x[c>>
2]=L.getProgramParameter(a,b);else Q||=1281},Ed=(a,b,c)=>{if(c){a=L.Ue.getQueryObjectEXT(wc[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;y[c>>2]=d;y[c+4>>2]=(d-y[c>>2])/4294967296}else Q||=1281},Fd=(a,b,c)=>{if(c){a=L.Ue.getQueryObjectEXT(wc[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else Q||=1281},Gd=(a,b,c,d)=>{a=L.getShaderInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,u,d,b):0;c&&(x[c>>2]=b)},Hd=(a,b,c)=>{c?35716==b?(a=L.getShaderInfoLog(N[a]),null===a&&(a="(unknown error)"),
x[c>>2]=a?a.length+1:0):35720==b?(a=L.getShaderSource(N[a]),x[c>>2]=a?a.length+1:0):x[c>>2]=L.getShaderParameter(N[a],b):Q||=1281},Id=a=>{var b=Xa(a)+1,c=R(b);c&&B(a,u,c,b);return c},Jd=()=>{var a=oc(L);return a=a.concat(a.map(b=>"GL_"+b))},Kd=a=>{var b=xc[a];if(!b){switch(a){case 7939:b=Id(Jd().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=L.getParameter(a))||(Q||=1280);b=b?Id(b):0;break;case 7938:b=Id(`OpenGL ES 2.0 (${L.getParameter(7938)})`);break;case 35724:b=L.getParameter(35724);
var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Id(b);break;default:Q||=1280}xc[a]=b}return b},Ld=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Md=a=>{var b=a.kf,c=a.pg,d;if(!b){a.kf=b={};a.og={};var e=L.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=L.getActiveUniform(a,d);var g=f.name;f=f.size;var l=Ld(g);l=0<l?g.slice(0,l):g;var q=a.Wf;a.Wf+=f;c[l]=[f,q];for(g=0;g<f;++g)b[q]=g,a.og[q++]=l}}},Nd=(a,b)=>{b=
b?A(u,b):"";if(a=M[a]){Md(a);var c=a.kf,d=0,e=b,f=Ld(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.pg[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||L.getUniformLocation(a,b)))return d}else Q||=1281;return-1},S=a=>{var b=L.wg;if(b){var c=b.kf[a];"number"==typeof c&&(b.kf[a]=c=L.getUniformLocation(b,b.og[a]+(0<c?`[${c}]`:"")));return c}Q||=1282},Od=(a,b,c,d)=>{if(c)if(a=M[a],Md(a),a=L.getUniform(a,S(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:z[c>>2]=a}else for(b=
0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b]}else Q||=1281},Pd=(a,b,c,d)=>{if(c)if(a=L.getVertexAttrib(a,b),34975==b)x[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:z[c>>2]=a;break;case 5:x[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b];break;case 5:x[c+4*b>>2]=Math.fround(a[b])}else Q||=1281},Qd=a=>{a=M[a];L.linkProgram(a);a.kf=0;a.pg={}},
Rd=(a,b)=>{3317==a?yc=b:3314==a&&(zc=b);L.pixelStorei(a,b)},Sd=(a,b,c,d,e)=>{a-=5120;a=1==a?u:4==a?x:6==a?z:5==a||28922==a?y:ra;b=d*((zc||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+yc-1&-yc);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Td=(a,b,c,d,e,f,g)=>{(g=Sd(f,e,c,d,g))?L.readPixels(a,b,c,d,e,f,g):Q||=1280},Ud=(a,b,c,d)=>L.renderbufferStorage(a,b,c,d),Vd=(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=y[c+4*f>>2])?A(u,
g,d?y[d+4*f>>2]:void 0):"";e+=g}L.shaderSource(N[a],e)},Wd=(a,b,c,d,e,f,g,l,q)=>{q=q?Sd(l,g,d,e,q):null;L.texImage2D(a,b,c,d,e,f,g,l,q)},Xd=(a,b,c)=>L.texParameterf(a,b,c),Yd=(a,b,c)=>L.texParameteri(a,b,c),Zd=(a,b,c,d,e,f,g,l,q)=>{q=q?Sd(l,g,e,f,q):null;L.texSubImage2D(a,b,c,d,e,f,g,l,q)},$d=[],ae=(a,b)=>{L.uniform1i(S(a),b)},be=[],ce=(a,b,c,d,e)=>{L.uniform4f(S(a),b,c,d,e)},de=(a,b,c,d)=>{if(18>=b){var e=$d[16*b],f=z;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+
2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=z.subarray(d>>2,d+64*b>>2);L.uniformMatrix4fv(S(a),!!c,e)},ee=a=>{a=M[a];L.useProgram(a);L.wg=a},fe=(a,b,c,d,e,f)=>{L.vertexAttribPointer(a,b,c,!!d,e,f)},ge=(a,b,c,d)=>L.viewport(a,b,c,d),he=()=>{try{if(navigator.getGamepads)return(J.tf=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=
null}return-1},je=(a,b,c,d)=>{J.zf||(J.zf=R(64));a=fc(a);return jc({target:a,Ff:!0,We:"click",ef:d,hf:(e=event)=>{var f=a,g=J.zf;sa[g>>3]=e.timeStamp;var l=g>>2;x[l+2]=e.screenX;x[l+3]=e.screenY;x[l+4]=e.clientX;x[l+5]=e.clientY;n[g+24]=e.ctrlKey;n[g+25]=e.shiftKey;n[g+26]=e.altKey;n[g+27]=e.metaKey;qa[2*l+14]=e.button;qa[2*l+15]=e.buttons;x[l+8]=e.movementX;x[l+9]=e.movementY;f=gc(f);x[l+10]=e.clientX-(f.left|0);x[l+11]=e.clientY-(f.top|0);ie(d,4,J.zf,b)&&e.preventDefault()},cf:c})},ke=(a,b,c,d,
e)=>{J.Kf||(J.Kf=R(276));return jc({target:a,We:e,ef:d,hf:(f=event)=>{var g=J.Kf,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,q=!!l;n[g]=q;n[g+1]=J.fullscreenEnabled();var t=q?l:J.Kg,p=t?.id||"";B(t?t==window?"#window":t==screen?"#screen":t?.nodeName||"":"",u,g+2,128);B(p,u,g+130,128);x[g+260>>2]=t?t.clientWidth:0;x[g+264>>2]=t?t.clientHeight:0;x[g+268>>2]=screen.width;x[g+272>>2]=screen.height;q&&(J.Kg=l);ie(d,19,g,b)&&
f.preventDefault()},cf:c})},le=(a,b,c,d,e)=>{J.Lf||(J.Lf=R(1240));b={target:fc(2),Ff:!0,We:e,ef:c,hf:(f=event)=>{var g=J.Lf;kc(g,f.gamepad);ie(c,d,g,a)&&f.preventDefault()},cf:b};return jc(b)},me=(a,b,c,d)=>{J.Vf||(J.Vf=R(36));a=fc(a);return jc({target:a,We:"resize",ef:d,hf:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=J.Vf;x[g>>2]=0;x[g+4>>2]=f.clientWidth;x[g+8>>2]=f.clientHeight;x[g+12>>2]=innerWidth;x[g+16>>2]=innerHeight;x[g+20>>2]=outerWidth;x[g+24>>2]=outerHeight;x[g+28>>2]=pageXOffset|
0;x[g+32>>2]=pageYOffset|0;ie(d,10,g,b)&&e.preventDefault()}}},cf:c})},ne=(a,b,c,d,e,f)=>{J.Uf||(J.Uf=R(1552));a=fc(a);return jc({target:a,Ff:"touchstart"==f||"touchend"==f,We:f,ef:d,hf:g=>{var l={},q=g.touches;for(var t of q)t.gg=t.kg=0,l[t.identifier]=t;for(var p of g.changedTouches)p.gg=1,l[p.identifier]=p;for(var r of g.targetTouches)l[r.identifier].kg=1;q=J.Uf;sa[q>>3]=g.timeStamp;n[q+12]=g.ctrlKey;n[q+13]=g.shiftKey;n[q+14]=g.altKey;n[q+15]=g.metaKey;t=q+16;p=gc(a);r=0;for(let v of Object.values(l))if(l=
t>>2,x[l]=v.identifier,x[l+1]=v.screenX,x[l+2]=v.screenY,x[l+3]=v.clientX,x[l+4]=v.clientY,x[l+5]=v.pageX,x[l+6]=v.pageY,n[t+28]=v.gg,n[t+29]=v.kg,x[l+8]=v.clientX-(p.left|0),x[l+9]=v.clientY-(p.top|0),t+=48,31<++r)break;x[q+8>>2]=r;ie(d,e,q,b)&&g.preventDefault()},cf:c})},oe=a=>{a instanceof Ea||"unwind"==a||fa(1,a)},pe=0,qe=a=>{oa=a;Ja||0<pe||(h.onExit?.(a),m=!0);fa(a,new Ea(a))},re=()=>{if(!(Ja||0<pe))try{var a=oa;oa=a;qe(a)}catch(b){oe(b)}},se=a=>{if(!m)try{a(),re()}catch(b){oe(b)}},te=(a,b)=>
setTimeout(()=>{se(a)},b),ue=!1,ve=!1,we=[];
function lb(){function a(){var c=h.canvas;ve=document.pointerLockElement===c||document.mozPointerLockElement===c||document.webkitPointerLockElement===c||document.msPointerLockElement===c}if(!xe){xe=!0;jb.push({canHandle:function(c){return!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:ye(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:ye(d)}));var l=URL.createObjectURL(g),q=new Image;q.onload=()=>{var t=document.createElement("canvas");
t.width=q.width;t.height=q.height;t.getContext("2d").drawImage(q,0,0);URL.revokeObjectURL(l);e?.(c)};q.onerror=()=>{k(`Image ${l} could not be decoded`);f?.()};q.src=l}});jb.push({canHandle:function(c){return!h.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e?.(c))}var g=!1,l=new Blob([c],{type:ye(d)});l=URL.createObjectURL(l);var q=new Audio;q.addEventListener("canplaythrough",()=>f(q),!1);q.onerror=function(){if(!g){k(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var t="data:audio/x-"+d.slice(-3)+";base64,",p="",r=0,v=0,C=0;C<c.length;C++)for(r=r<<8|c[C],v+=8;6<=v;){var D=r>>v-6&63;v-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[D]}2==v?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&3)<<4],p+="=="):4==v&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&15)<<2],p+="=");q.src=t+p;f(q)}};q.src=l;te(()=>{f(q)},1E4)}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||
b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&
b.addEventListener("click",c=>{!ve&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}function ze(a){var b={antialias:1<Ae[135181],depth:0<Ae[135173],stencil:0<Ae[135174],alpha:0<Ae[135172]};if(!h.ctx||a!=h.canvas){var c,d={antialias:!1,alpha:!1,Hg:1};if(b)for(var e in b)d[e]=b[e];if("undefined"!=typeof Hc&&(c=Ec(a,d)))var f=vc[c].Df;f&&(h.ctx=f,Gc=vc[c],h.ctx=L=Gc?.Df,we.forEach(g=>g()),lb())}}var Be=!1,Ce=void 0,T=void 0;
function De(a,b){function c(){ue=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Ee,Ce&&d.requestPointerLock(),ue=!0,T?Fe():U(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),T?Ge():U(d));h.onFullScreen?.(ue);h.onFullscreen?.(ue)}Ce=a;T=b;"undefined"==typeof Ce&&(Ce=!0);"undefined"==typeof T&&(T=!1);var d=h.canvas;Be||(Be=!0,
document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?
()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}function Ee(){if(!ue)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}function ye(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}var He=0,Ie=0,Je=0,Ke=0;
function Le(a,b){var c=h.canvas,d=c.getBoundingClientRect();a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+d.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+d.top;a*=c.width/d.width;b*=c.height/d.height;return{x:a,y:b}}function Me(a,b){const {x:c,y:d}=Le(a,b);Je=c-He;Ke=d-Ie;He=c;Ie=d}
function Ne(a){ve?("mousemove"!=a.type&&"mozMovementX"in a?Je=Ke=0:(Je=a.movementX||a.mozMovementX||a.webkitMovementX||0,Ke=a.movementY||a.mozMovementY||a.webkitMovementY||0),He+=Je,Ie+=Ke):"touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type?(a=a.uh,void 0!==a&&Le(a.pageX,a.pageY)):Me(a.pageX,a.pageY)}var Oe=[];function Pe(){var a=h.canvas;Oe.forEach(b=>b(a.width,a.height))}function Fe(){"undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]|8388608);U(h.canvas);Pe()}
function Ge(){"undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]&-8388609);U(h.canvas);Pe()}
function U(a,b,c){b&&c?(a.Xf=b,a.Nf=c):(b=a.Xf,c=a.Nf);var d=b,e=c;0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*f)}T?(a.width!=d&&(a.width=
d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var kb={},xe,Qe={},Se=()=>{if(!Re){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Qe)void 0===Qe[b]?delete a[b]:a[b]=Qe[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Re=c}return Re},Re;
function Te(a,b,c,d,e,f){this.id=a;this.y=this.x=0;this.rf=!1;this.ng=this.mg=0;this.width=b;this.height=c;this.Jf=d;this.If=e;this.Sf=b;this.Rf=c;this.title=f;this.attributes={...Ae};this.buttons=0;this.keys=[];this.Gf=[];this.Lg=0;this.title=null;this.pf=this.sf=this.gf=this.Bf=this.af=this.ff=this.yf=this.rg=this.eg=this.tg=this.sg=this.qg=this.Cf=0}
var cf=(a,b)=>{Ue=a;Ve=b;if(We)if(Xe||=!0,0==a)Ye=function(){setTimeout(Ze,Math.max(0,$e+b-performance.now())|0)};else if(1==a)Ye=function(){af(Ze)};else if(2==a){if("undefined"==typeof bf)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);bf=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate",
"*")}}else bf=setImmediate;Ye=function(){bf(Ze)}}},lf=a=>{function b(){return c<df?(re(),!1):!0}We=a;var c=df;Xe=!1;Ze=function(){if(!m)if(0<ef.length){var d=ef.shift();d.jh(d.Qg);if(ff){var e=ff,f=0==e%1?e-1:Math.floor(e);ff=d.$g?f:(8*e+(f+.5))/9}h.setStatus&&(d=h.statusMessage||"Please wait...",e=ff??0,f=gf.gh??0,e?e<f?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(d):h.setStatus(""));b()&&setTimeout(Ze,0)}else if(b())if(hf=hf+1|0,1==Ue&&1<Ve&&0!=hf%Ve)Ye();else{0==Ue&&
($e=performance.now());a:if(!m){for(d of jf)if(!1===d())break a;se(a);for(e of kf)e()}b()&&Ye()}}},Xe=!1,Ye=null,df=0,We=null,Ue=0,Ve=0,hf=0,ef=[],jf=[],kf=[];function mf(){Ye=null;df++}function nf(){df++;var a=Ue,b=Ve,c=We;We=null;lf(c);cf(a,b);Ye()}var of=0;function af(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===of)of=b+1E3/60;else for(;b+2>=of;)of+=1E3/60;setTimeout(a,Math.max(of-b,0))}}
var gf={},$e,Ze,bf,ff,X=a=>0>=a||!W?null:W[a-1],pf=0,Y=null,qf=null,W=null,rf=null,sf=null,Ae=null,tf=null,uf={131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0},vf=a=>{switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;
case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;
case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;
case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;
case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 224:return 343;
case 93:return 348;default:return-1}},wf=()=>{var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);if(a.keys[343]||a.keys[348])b|=8;return b},xf=a=>{Y&&Y.pf&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||dynCall_vii(Y.pf,Y.id,a))},zf=(a,b)=>{if(Y){var c=vf(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.Gf[a]=b;Y.sf&&(d&&(b=2),yf(Y.sf,Y.id,c,a,b,wf()))}}},Bf=()=>{Af()},Cf=()=>{Af()},Df=a=>{zf(a.keyCode,1);"Backspace"!=a.key&&"Tab"!=a.key||a.preventDefault()},Ef=a=>{zf(a.keyCode,
0)},Ff=()=>{if(Y)for(var a=0;a<Y.Gf.length;++a)Y.Gf[a]&&zf(a,0)},Hf=a=>{if(Y){if("touchmove"===a.type){a.preventDefault();let b=!1;for(let c of a.changedTouches)if(tf===c.identifier){Me(c.pageX,c.pageY);b=!0;break}if(!b)return}else Ne(a);a.target==h.canvas&&Y.ff&&Y.ff&&Gf(Y.ff,Y.id,He,Ie)}},If=a=>{Y&&a.target==h.canvas&&Y.af&&dynCall_vii(Y.af,Y.id,1)},Jf=a=>{Y&&a.target==h.canvas&&Y.af&&dynCall_vii(Y.af,Y.id,0)},Nf=(a,b)=>{if(Y&&a.target==h.canvas){var c=0;if("touchstart"===a.type||"touchend"===a.type||
"touchcancel"===a.type){a.preventDefault();var d=!1;if(null===tf&&"touchstart"===a.type&&0<a.targetTouches.length)d=a.targetTouches[0],tf=d.identifier,Me(d.pageX,d.pageY),d=!0;else if("touchend"===a.type||"touchcancel"===a.type)for(let e of a.changedTouches)if(tf===e.identifier){tf=null;d=!0;break}if(!d)return}else Ne(a),c=a.button,0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(e){}}else Y.buttons&=~(1<<c);Y.yf&&Mf(Y.yf,Y.id,c,b,wf())}},Of=a=>{Y&&Nf(a,1)},Pf=a=>{Y&&Nf(a,
0)},Qf=a=>{switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);Y&&Y.Bf&&a.target==h.canvas&&(Gf(Y.Bf,Y.id,"mousewheel"==a.type?a.wheelDeltaX:a.deltaX,b),a.preventDefault())},
Sf=(a,b,c,d)=>{if(Y){var e=!1;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?Y.rf||(e=a!=screen.width||b!=screen.height,Y.mg=Y.x,Y.ng=Y.y,Y.Sf=Y.width,Y.Rf=Y.height,Y.x=Y.y=0,Y.width=screen.width,Y.height=screen.height,Y.rf=!0):1==Y.rf&&(e=a!=Y.Sf||b!=Y.Rf,Y.x=Y.mg,Y.y=Y.ng,Y.width=Y.Sf,Y.height=Y.Rf,Y.rf=!1);if(e)U(h.canvas,Y.width,Y.height),Pe();else if(Y.width!=a||Y.height!=b||Y.Jf!=c||Y.If!=d)Y.width=a,Y.height=b,Y.Jf=c,Y.If=d,Y&&Y.Cf&&Rf(Y.Cf,Y.id,
Y.width,Y.height),Y&&Y.eg&&Rf(Y.eg,Y.id,Y.Jf,Y.If)}},Tf={},Uf=[],Vf=null,Af=()=>{if(hf!==Vf||!hf){Uf=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads||[];Vf=hf;for(var a=0;a<Uf.length;++a){var b=Uf[a];if(b){Tf[a]||(ma("glfw joystick connected:",a),Tf[a]={id:Id(b.id),Tg:b.buttons.length,Rg:b.axes.length,buttons:R(b.buttons.length),axes:R(4*b.axes.length)});for(var c=Tf[a],d=0;d<b.buttons.length;++d)n[c.buttons+d]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)z[c.axes+4*
d>>2]=b.axes[d]}else Tf[a]&&(ma("glfw joystick disconnected",a),Wf(Tf[a].id),Wf(Tf[a].buttons),Wf(Tf[a].axes),delete Tf[a])}}},Xf=a=>{function b(l){var q="/.glfw_dropped_files/"+l.name.replace(/\//g,"_"),t=new FileReader;t.onloadend=r=>{if(2!=t.readyState)++f,ma("failed to read dropped file: "+l.name+": "+t.error);else{r=new Uint8Array(r.target.result);var v={};v.flags=v.flags||577;var C=Rb(q,v.flags,v.mode);"string"==typeof r&&(r=new Uint8Array(Ya(r)));if(ArrayBuffer.isView(r))Ub(C,r,0,r.byteLength,
void 0,v.Zg);else throw Error("Unsupported data type");Sb(C);if(++f===e){Rf(Y.gf,Y.id,e,c);for(r=0;r<d.length;++r)Wf(d[r]);Wf(c)}}};t.readAsArrayBuffer(l);var p=Id(q);d.push(p);y[c+4*g>>2]=p}if(Y&&Y.gf&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=R(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,f=0;Vb("/",".glfw_dropped_files");for(var g=0;g<e;++g)b(a.dataTransfer.files[g]);return!1}},Yf=a=>{if(Y&&Y.gf)return a.preventDefault(),
!1};
function Zf(a,b){function c(){ue=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Ee,Ce&&d.requestPointerLock(),ue=!0,T?Fe():(U(d),Pe())):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),T?Ge():(U(d),Pe()));h.onFullScreen?.(ue);h.onFullscreen?.(ue)}Ce=a;T=b;"undefined"==typeof Ce&&(Ce=!0);"undefined"==typeof T&&(T=!1);var d=h.canvas;
Be||(Be=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?
()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function $f(a,b,c){var d=ag()?qf:1;b&&c?(a.Xf=b,a.Nf=c):(b=a.Xf,c=a.Nf);var e=b,f=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(e/f<h.forcedAspectRatio?e=Math.round(f*h.forcedAspectRatio):f=Math.round(e/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/e,screen.height/f);e=Math.round(e*g);
f=Math.round(f*g)}T&&(b=e,c=f);e=Math.floor(b*d);d=Math.floor(c*d);a.width!=e&&(a.width=e);a.height!=d&&(a.height=d);"undefined"!=typeof a.style&&(ag()?(a.style.setProperty("width",b+"px","important"),a.style.setProperty("height",c+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height")))}
function bg(a,b){const c=h.canvas.getBoundingClientRect();a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+c.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+c.top;!ag()&&Y&&(a*=Y.width/c.width,b*=Y.height/c.height);return{x:a,y:b}}function cg(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1}function ag(){return Y?0<Y.attributes[139276]:!1}function dg(){Y&&(U(h.canvas,Y.width,Y.height),Pe())}
function eg(){qf=cg();Y&&Y.rg&&fg(Y.rg,Y.id,qf,qf);dg()}var gg=a=>{try{a()}catch(b){za(b)}};function hg(a){var b=(...c)=>{ig.push(a);try{return a(...c)}finally{m||(ig.pop(),Z&&1===jg&&0===ig.length&&(jg=0,gg(kg),"undefined"!=typeof Fibers&&Fibers.vh()))}};lg.set(a,b);return b}var jg=0,Z=null,mg=0,ig=[],ng=new Map,og=new Map,lg=new Map,pg=0,qg=null,rg=[];function sg(){return new Promise((a,b)=>{qg={resolve:a,reject:b}})}
function tg(){var a=R(4108),b=a+12;y[a>>2]=b;y[a+4>>2]=b+4096;b=ig[0];if(!ng.has(b)){var c=pg++;ng.set(b,c);og.set(c,b)}b=ng.get(b);x[a+8>>2]=b;return a}function ug(){var a=og.get(x[Z+8>>2]);return lg.get(a)()}
function vg(a){if(!m){if(0===jg){var b=!1,c=!1;a((d=0)=>{if(!m&&(mg=d,b=!0,c)){jg=2;gg(()=>wg(Z));"undefined"!=typeof gf&&We&&nf();d=!1;try{var e=ug()}catch(l){e=l,d=!0}var f=!1;if(!Z){var g=qg;g&&(qg=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(jg=1,Z=tg(),"undefined"!=typeof gf&&We&&mf(),gg(()=>xg(Z)))}else 2===jg?(jg=0,gg(yg),Wf(Z),Z=null,rg.forEach(se)):za(`invalid state: ${jg}`);return mg}}sb=Array(4096);Ib(F,"/");I("/tmp");I("/home");I("/home/web_user");
(function(){I("/dev");ab(259,{read:()=>0,write:(d,e,f,g)=>g,Qe:()=>0});Nb("/dev/null",259);$a(1280,cb);$a(1536,db);Nb("/dev/tty",1280);Nb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ua(a),b=a.byteLength);return a[--b]};Yb("/dev","random",c);Yb("/dev","urandom",c);I("/dev/shm");I("/dev/shm/tmp")})();
(function(){I("/proc");var a=I("/proc/self");I("/proc/self/fd");Ib({Xe(){var b=fb(a,"fd",16895,73);b.Je={Qe:F.Je.Qe};b.Ke={lookup(c,d){c=+d;var e=Eb(c);c={parent:null,Xe:{ig:"fake"},Ke:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(qb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();F.cg=new E(44);F.cg.stack="<generic error, no stack>";for(let a=0;32>a;++a)md.push(Array(a));
for(var zg=new Float32Array(288),Ag=0;288>=Ag;++Ag)$d[Ag]=zg.subarray(0,Ag);var Bg=new Int32Array(288);for(Ag=0;288>=Ag;++Ag)be[Ag]=Bg.subarray(0,Ag);h.requestAnimationFrame=af;h.pauseMainLoop=mf;h.resumeMainLoop=nf;h.preMainLoop&&jf.push(h.preMainLoop);h.postMainLoop&&kf.push(h.postMainLoop);h.noExitRuntime&&(Ja=h.noExitRuntime);h.preloadPlugins&&(jb=h.preloadPlugins);h.print&&(ma=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(na=h.wasmBinary);h.thisProgram&&(ea=h.thisProgram);
h.addRunDependency=xa;h.removeRunDependency=ya;
h.ccall=(a,b,c,d,e)=>{function f(r){--pe;0!==q&&Cg(q);return"string"===b?r?A(u,r):"":"boolean"===b?!!r:r}var g={string:r=>{var v=0;if(null!==r&&void 0!==r&&0!==r){v=Xa(r)+1;var C=Dg(v);B(r,u,C,v);v=C}return v},array:r=>{var v=Dg(r.length);n.set(r,v);return v}};a=h["_"+a];var l=[],q=0;if(d)for(var t=0;t<d.length;t++){var p=g[c[t]];p?(0===q&&(q=Eg()),l[t]=p(d[t])):l[t]=d[t]}c=Z;d=a(...l);e=e?.async;pe+=1;if(Z!=c)return sg().then(f);d=f(d);return e?Promise.resolve(d):d};
h.FS_createPreloadedFile=(a,b,c,d,e,f,g,l,q,t)=>{function p(C){function D(w){t?.();l||Xb(a,b,w,d,e,q);f?.();ya(v)}mb(C,r,D,()=>{g?.();ya(v)})||D(C)}var r=b?Va(Ra(a+"/"+b)):a,v=`cp ${r}`;xa(v);"string"==typeof c?ib(c).then(p,g):p(c)};h.FS_unlink=(...a)=>Pb(...a);h.FS_createPath=(...a)=>Vb(...a);h.FS_createDevice=(...a)=>Yb(...a);h.FS_createDataFile=(...a)=>Xb(...a);h.FS_createLazyFile=(...a)=>$b(...a);
var Fg,R,Wf,Cg,Dg,Eg,dynCall_vii,Rf,yf,Mf,Gf,ie,dynCall_vi,dynCall_v,dynCall_iii,fg,xg,kg,wg,yg,Gg={sa:function(){return window.innerHeight},ta:function(){return window.innerWidth},p:(a,b,c,d)=>za(`Assertion failed: ${a?A(u,a):""}, at: `+[b?b?A(u,b):"":"unknown filename",c,d?d?A(u,d):"":"unknown function"]),j:(a,b,c)=>{var d=new La(a);y[d.Af+16>>2]=0;y[d.Af+4>>2]=b;y[d.Af+8>>2]=c;Oa=a;Pa++;throw Oa;},Za:function(a,b,c){try{b=b?A(u,b):"";b=bc(a,b);if(c&-8)return-28;var d=yb(b,{qf:!0}).node;if(!d)return-44;
a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&Bb(d,a)?-2:0}catch(e){if("undefined"==typeof ac||"ErrnoError"!==e.name)throw e;return-e.Ne}},M:function(a,b,c){cc=c;try{var d=Eb(a);switch(b){case 0:var e=dc();if(0>e)break;for(;qb[e];)e++;return Gb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=dc(),d.flags|=e,0;case 12:return e=dc(),qa[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof ac||"ErrnoError"!==f.name)throw f;return-f.Ne}},Ta:function(a,
b){try{if(0===b)return-28;var c=Xa("/")+1;if(b<c)return-68;B("/",u,a,b);return c}catch(d){if("undefined"==typeof ac||"ErrnoError"!==d.name)throw d;return-d.Ne}},Va:function(a,b,c){cc=c;try{var d=Eb(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Ye.Cg){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=dc();x[e>>2]=25856;x[e+4>>2]=5;x[e+8>>2]=191;x[e+12>>2]=35387;for(var f=0;32>f;f++)n[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?
0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Ye.Dg)for(e=dc(),a=[],f=0;32>f;f++)a.push(n[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=dc();return x[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=dc();if(!d.Je.Bg)throw new E(59);return d.Je.Bg(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Ye.Eg&&(f=[24,80],e=dc(),qa[e>>1]=f[0],qa[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof ac||
"ErrnoError"!==g.name)throw g;return-g.Ne}},Wa:function(a,b,c,d){cc=d;try{b=b?A(u,b):"";b=bc(a,b);var e=d?dc():0;return Rb(b,c,e).fd}catch(f){if("undefined"==typeof ac||"ErrnoError"!==f.name)throw f;return-f.Ne}},Qa:()=>za(""),Na:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();y[a>>2]=60*Math.max(f,e);x[b>>2]=Number(f!=e);b=g=>{var l=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%
60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(B(a,u,c,17),B(b,u,d,17)):(B(a,u,d,17),B(b,u,c,17))},Ya:function(a,b,c){if(!(0<=a&&3>=a))return 28;ta[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},Xa:()=>Date.now(),me:(a,b,c)=>{a=fc(a);if(!a)return-4;a=gc(a);sa[b>>3]=a.width;sa[c>>3]=a.height;return 0},ma:(a,b)=>{if(0>a||a>=J.tf.length)return-5;if(!J.tf[a])return-7;kc(b,J.tf[a]);return 0},J:()=>performance.now(),na:()=>J.tf.length,Rd:Ic,Qd:Jc,ge:(a,b)=>{L.Ue.beginQueryEXT(a,
wc[b])},Pd:Kc,Nd:Lc,Md:Mc,Ld:Nc,Kd:Oc,_d:a=>{L.bindVertexArray(uc[a])},Jd:(a,b,c,d)=>L.blendColor(a,b,c,d),Id:a=>L.blendEquation(a),Hd:(a,b)=>L.blendEquationSeparate(a,b),Gd:Pc,Fd:(a,b,c,d)=>L.blendFuncSeparate(a,b,c,d),Ed:Qc,Dd:Rc,Cd:Sc,Bd:Tc,Ad:Uc,zd:Vc,yd:a=>L.clearStencil(a),$a:(a,b)=>{L.yg.clipControlEXT(a,b)},xd:(a,b,c,d)=>{L.colorMask(!!a,!!b,!!c,!!d)},wd:Wc,vd:Xc,ud:(a,b,c,d,e,f,g,l,q)=>{L.compressedTexSubImage2D(a,b,c,d,e,f,g,u.subarray(q,q+l))},td:(a,b,c,d,e,f,g,l)=>L.copyTexImage2D(a,b,
c,d,e,f,g,l),sd:(a,b,c,d,e,f,g,l)=>L.copyTexSubImage2D(a,b,c,d,e,f,g,l),rd:Yc,qd:Zc,pd:$c,od:ad,nd:bd,md:cd,ie:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=wc[d];e&&(L.Ue.deleteQueryEXT(e),wc[d]=null)}},ld:dd,kd:ed,jd:fd,Yd:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2];L.deleteVertexArray(uc[d]);uc[d]=null}},id:gd,hd:a=>{L.depthMask(!!a)},gd:(a,b)=>L.depthRange(a,b),fd:hd,ed:jd,dd:kd,cd:ld,Ud:(a,b,c,d)=>{L.drawArraysInstanced(a,b,c,d)},Vd:(a,b)=>{for(var c=md[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];
L.drawBuffers(c)},bd:nd,Td:(a,b,c,d,e)=>{L.drawElementsInstanced(a,b,c,d,e)},ad:od,$c:pd,fe:a=>{L.Ue.endQueryEXT(a)},_c:()=>L.finish(),Zc:()=>L.flush(),Yc:qd,Xc:rd,Wc:sd,Vc:td,Tc:ud,je:(a,b)=>{for(var c=0;c<a;c++){var d=L.Ue.createQueryEXT();if(!d){for(Q||=1282;c<a;)x[b+4*c++>>2]=0;break}var e=Ac(wc);d.name=e;wc[e]=d;x[b+4*c>>2]=e}},Sc:vd,Qc:wd,Xd:(a,b)=>{Bc(a,b,"createVertexArray",uc)},Uc:a=>L.generateMipmap(a),Pc:(a,b,c,d,e,f,g)=>xd("getActiveAttrib",a,b,c,d,e,f,g),Oc:(a,b,c,d,e,f,g)=>xd("getActiveUniform",
a,b,c,d,e,f,g),Nc:(a,b,c,d)=>{a=L.getAttachedShaders(M[a]);var e=a.length;e>b&&(e=b);x[c>>2]=e;for(b=0;b<e;++b)x[d+4*b>>2]=N.indexOf(a[b])},Mc:yd,Lc:(a,b)=>zd(a,b,4),Kc:(a,b,c)=>{c?x[c>>2]=L.getBufferParameter(a,b):Q||=1281},Jc:()=>{var a=L.getError()||Q;Q=0;return a},Ic:Ad,Hc:Bd,Fc:(a,b)=>zd(a,b,0),Dc:Cd,Ec:Dd,ae:Ed,ce:Fd,$d:Ed,be:Fd,de:(a,b,c)=>{c?x[c>>2]=L.Ue.getQueryEXT(a,b):Q||=1281},Cc:(a,b,c)=>{c?x[c>>2]=L.getRenderbufferParameter(a,b):Q||=1281},Ac:Gd,zc:(a,b,c,d)=>{a=L.getShaderPrecisionFormat(a,
b);x[c>>2]=a.rangeMin;x[c+4>>2]=a.rangeMax;x[d>>2]=a.precision},yc:(a,b,c,d)=>{if(a=L.getShaderSource(N[a]))b=0<b&&d?B(a,u,d,b):0,c&&(x[c>>2]=b)},Bc:Hd,xc:Kd,wc:(a,b,c)=>{c?z[c>>2]=L.getTexParameter(a,b):Q||=1281},uc:(a,b,c)=>{c?x[c>>2]=L.getTexParameter(a,b):Q||=1281},rc:Nd,tc:(a,b,c)=>{Od(a,b,c,2)},sc:(a,b,c)=>{Od(a,b,c,0)},oc:(a,b,c)=>{c?x[c>>2]=L.getVertexAttribOffset(a,b):Q||=1281},qc:(a,b,c)=>{Pd(a,b,c,2)},pc:(a,b,c)=>{Pd(a,b,c,5)},nc:(a,b)=>L.hint(a,b),mc:a=>(a=qc[a])?L.isBuffer(a):0,lc:a=>
L.isEnabled(a),kc:a=>(a=rc[a])?L.isFramebuffer(a):0,jc:a=>(a=M[a])?L.isProgram(a):0,he:a=>(a=wc[a])?L.Ue.isQueryEXT(a):0,ic:a=>(a=sc[a])?L.isRenderbuffer(a):0,hc:a=>(a=N[a])?L.isShader(a):0,gc:a=>(a=tc[a])?L.isTexture(a):0,Wd:a=>(a=uc[a])?L.isVertexArray(a):0,fc:a=>L.lineWidth(a),ec:Qd,dc:Rd,_a:(a,b)=>{L.Ng.polygonModeWEBGL(a,b)},cc:(a,b)=>L.polygonOffset(a,b),bb:(a,b,c)=>{L.zg.polygonOffsetClampEXT(a,b,c)},ee:(a,b)=>{L.Ue.queryCounterEXT(wc[a],b)},bc:Td,ac:()=>{},$b:Ud,_b:(a,b)=>{L.sampleCoverage(a,
!!b)},Zb:(a,b,c,d)=>L.scissor(a,b,c,d),Yb:()=>{Q||=1280},Xb:Vd,Wb:(a,b,c)=>L.stencilFunc(a,b,c),Vb:(a,b,c,d)=>L.stencilFuncSeparate(a,b,c,d),Ub:a=>L.stencilMask(a),Tb:(a,b)=>L.stencilMaskSeparate(a,b),Rb:(a,b,c)=>L.stencilOp(a,b,c),Qb:(a,b,c,d)=>L.stencilOpSeparate(a,b,c,d),Pb:Wd,Ob:Xd,Nb:(a,b,c)=>{L.texParameterf(a,b,z[c>>2])},Mb:Yd,Lb:(a,b,c)=>{L.texParameteri(a,b,x[c>>2])},Kb:Zd,Jb:(a,b)=>{L.uniform1f(S(a),b)},Ib:(a,b,c)=>{if(288>=b)for(var d=$d[b],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>
2,c+4*b>>2);L.uniform1fv(S(a),d)},Gb:ae,Fb:(a,b,c)=>{if(288>=b)for(var d=be[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);L.uniform1iv(S(a),d)},Eb:(a,b,c)=>{L.uniform2f(S(a),b,c)},Db:(a,b,c)=>{if(144>=b){b*=2;for(var d=$d[b],e=0;e<b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2]}else d=z.subarray(c>>2,c+8*b>>2);L.uniform2fv(S(a),d)},Cb:(a,b,c)=>{L.uniform2i(S(a),b,c)},Bb:(a,b,c)=>{if(144>=b){b*=2;for(var d=be[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>
2,c+8*b>>2);L.uniform2iv(S(a),d)},Ab:(a,b,c,d)=>{L.uniform3f(S(a),b,c,d)},zb:(a,b,c)=>{if(96>=b){b*=3;for(var d=$d[b],e=0;e<b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2]}else d=z.subarray(c>>2,c+12*b>>2);L.uniform3fv(S(a),d)},yb:(a,b,c,d)=>{L.uniform3i(S(a),b,c,d)},xb:(a,b,c)=>{if(96>=b){b*=3;for(var d=be[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);L.uniform3iv(S(a),d)},vb:ce,ub:(a,b,c)=>{if(72>=b){var d=
$d[4*b],e=z;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=z.subarray(c>>2,c+16*b>>2);L.uniform4fv(S(a),d)},tb:(a,b,c,d,e)=>{L.uniform4i(S(a),b,c,d,e)},sb:(a,b,c)=>{if(72>=b){b*=4;for(var d=be[b],e=0;e<b;e+=4)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2],d[e+3]=x[c+(4*e+12)>>2]}else d=x.subarray(c>>2,c+16*b>>2);L.uniform4iv(S(a),d)},rb:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=$d[b],f=0;f<b;f+=4)e[f]=z[d+4*f>>2],e[f+1]=z[d+(4*f+4)>>
2],e[f+2]=z[d+(4*f+8)>>2],e[f+3]=z[d+(4*f+12)>>2]}else e=z.subarray(d>>2,d+16*b>>2);L.uniformMatrix2fv(S(a),!!c,e)},qb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=$d[b],f=0;f<b;f+=9)e[f]=z[d+4*f>>2],e[f+1]=z[d+(4*f+4)>>2],e[f+2]=z[d+(4*f+8)>>2],e[f+3]=z[d+(4*f+12)>>2],e[f+4]=z[d+(4*f+16)>>2],e[f+5]=z[d+(4*f+20)>>2],e[f+6]=z[d+(4*f+24)>>2],e[f+7]=z[d+(4*f+28)>>2],e[f+8]=z[d+(4*f+32)>>2]}else e=z.subarray(d>>2,d+36*b>>2);L.uniformMatrix3fv(S(a),!!c,e)},pb:de,ob:ee,nb:a=>{L.validateProgram(M[a])},mb:(a,b)=>
L.vertexAttrib1f(a,b),kb:(a,b)=>{L.vertexAttrib1f(a,z[b>>2])},jb:(a,b,c)=>L.vertexAttrib2f(a,b,c),ib:(a,b)=>{L.vertexAttrib2f(a,z[b>>2],z[b+4>>2])},hb:(a,b,c,d)=>L.vertexAttrib3f(a,b,c,d),gb:(a,b)=>{L.vertexAttrib3f(a,z[b>>2],z[b+4>>2],z[b+8>>2])},fb:(a,b,c,d,e)=>L.vertexAttrib4f(a,b,c,d,e),eb:(a,b)=>{L.vertexAttrib4f(a,z[b>>2],z[b+4>>2],z[b+8>>2],z[b+12>>2])},Sd:(a,b)=>{L.vertexAttribDivisor(a,b)},db:fe,cb:ge,Ra:a=>{var b=u.length;a>>>=0;if(536870912<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+
.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(536870912,65536*Math.ceil(Math.max(a,d)/65536))-pa.buffer.byteLength+65535)/65536|0;try{pa.grow(d);ua();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},oa:he,ra:(a,b,c)=>{a=fc(a);if(!a)return-4;a.width=b;a.height=c;return 0},U:(a,b,c,d)=>je(a,b,c,d),W:(a,b,c,d)=>{if(!J.fullscreenEnabled())return-1;a=fc(a);if(!a)return-4;ke(a,b,c,d,"webkitfullscreenchange");return ke(a,b,c,d,"fullscreenchange")},pe:(a,b,c)=>he()?-1:le(a,b,c,26,"gamepadconnected"),
oe:(a,b,c)=>he()?-1:le(a,b,c,27,"gamepaddisconnected"),V:(a,b,c,d)=>me(a,b,c,d),qe:(a,b,c,d)=>ne(a,b,c,d,25,"touchcancel"),S:(a,b,c,d)=>ne(a,b,c,d,23,"touchend"),re:(a,b,c,d)=>ne(a,b,c,d,24,"touchmove"),T:(a,b,c,d)=>ne(a,b,c,d,22,"touchstart"),ua:a=>document.title=a?A(u,a):"",va:a=>vg(b=>te(b,a)),Oa:(a,b)=>{var c=0,d=0,e;for(e of Se()){var f=b+c;y[a+d>>2]=f;c+=B(e,u,f,Infinity)+1;d+=4}return 0},Pa:(a,b)=>{var c=Se();y[a>>2]=c.length;a=0;for(var d of c)a+=Xa(d)+1;y[b>>2]=a;return 0},ke:a=>{oa=a;qe(a)},
N:function(a){try{var b=Eb(a);Sb(b);return 0}catch(c){if("undefined"==typeof ac||"ErrnoError"!==c.name)throw c;return c.Ne}},Ua:function(a,b,c,d){try{a:{var e=Eb(a);a=b;for(var f,g=b=0;g<c;g++){var l=y[a>>2],q=y[a+4>>2];a+=8;var t=e,p=l,r=q,v=f,C=n;if(0>r||0>v)throw new E(28);if(null===t.fd)throw new E(8);if(1===(t.flags&2097155))throw new E(8);if(H(t.node.mode))throw new E(31);if(!t.Je.read)throw new E(28);var D="undefined"!=typeof v;if(!D)v=t.position;else if(!t.seekable)throw new E(70);var w=t.Je.read(t,
C,p,r,v);D||(t.position+=w);var G=w;if(0>G){var P=-1;break a}b+=G;if(G<q)break;"undefined"!=typeof f&&(f+=G)}P=b}y[d>>2]=P;return 0}catch(O){if("undefined"==typeof ac||"ErrnoError"!==O.name)throw O;return O.Ne}},Sa:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=Eb(a);Tb(e,b,c);ta[d>>3]=BigInt(e.position);e.Mf&&0===b&&0===c&&(e.Mf=null);return 0}catch(f){if("undefined"==typeof ac||"ErrnoError"!==f.name)throw f;return f.Ne}},L:function(a,b,
c,d){try{a:{var e=Eb(a);a=b;for(var f,g=b=0;g<c;g++){var l=y[a>>2],q=y[a+4>>2];a+=8;var t=Ub(e,n,l,q,f);if(0>t){var p=-1;break a}b+=t;if(t<q)break;"undefined"!=typeof f&&(f+=t)}p=b}y[d>>2]=p;return 0}catch(r){if("undefined"==typeof ac||"ErrnoError"!==r.name)throw r;return r.Ne}},R:Ic,B:Jc,g:Kc,b:Lc,e:Mc,E:Nc,d:Oc,Sb:Pc,n:Qc,v:Rc,Da:Sc,O:Tc,P:Uc,lb:Vc,Aa:Wc,Ma:Xc,ya:Yc,Ca:Zc,Gc:$c,l:ad,Ea:bd,F:cd,Fa:dd,G:ed,s:fd,Hb:gd,H:hd,Rc:jd,m:kd,Zd:ld,Od:nd,Q:od,f:pd,q:qd,k:rd,wb:sd,o:td,Ha:ud,La:vd,K:wd,u:yd,
vc:Ad,D:Bd,wa:Cd,A:Dd,za:Gd,C:Hd,i:Kd,t:Nd,xa:Qd,ab:Rd,Ia:Td,Ka:Ud,Ba:Vd,I:Wd,w:Xd,c:Yd,Ja:Zd,aa:ae,ia:ce,Ga:de,r:ee,h:fe,se:ge,y:(a,b,c,d)=>{var e;for(e=0;e<W.length&&null!==W[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||0>=b)f=0;else{d?De():(U(h.canvas,a,b),Pe());for(e=0;e<W.length&&null==W[e];e++);d=h.canvas;var g=0<Ae[139265];e==W.length&&(g?ze(d):lb());!h.ctx&&g?f=0:(a=new Te(f,a,b,d.width,d.height,c),f-1==W.length?W.push(a):W[f-1]=a,Y=
a,dg(),f=a.id)}return f},ja:()=>{Ae={...uf}},le:a=>{a:{if(a=X(a)){a.qg&&dynCall_vi(a.qg,a.id);W[a.id-1]=null;Y.id==a.id&&(Y=null);for(a of W)if(null!==a){a=void 0;break a}delete h.ctx}a=void 0}return a},z:()=>1,pa:()=>performance.now()/1E3-rf,ha:(a,b)=>x[b>>2]=0,ka:()=>{if(W)return 1;rf=performance.now()/1E3;Ae={...uf};W=[];Y=null;qf=cg();window.addEventListener("gamepadconnected",Bf,!0);window.addEventListener("gamepaddisconnected",Cf,!0);window.addEventListener("keydown",Df,!0);window.addEventListener("keypress",
xf,!0);window.addEventListener("keyup",Ef,!0);window.addEventListener("blur",Ff,!0);sf=window.matchMedia("(resolution: "+cg()+"dppx)");sf.addEventListener("change",eg);var a=h.canvas;a.addEventListener("touchmove",Hf,!0);a.addEventListener("touchstart",Of,!0);a.addEventListener("touchcancel",Pf,!0);a.addEventListener("touchend",Pf,!0);a.addEventListener("mousemove",Hf,!0);a.addEventListener("mousedown",Of,!0);a.addEventListener("mouseup",Pf,!0);a.addEventListener("wheel",Qf,!0);a.addEventListener("mousewheel",
Qf,!0);a.addEventListener("mouseenter",If,!0);a.addEventListener("mouseleave",Jf,!0);a.addEventListener("drop",Xf,!0);a.addEventListener("dragover",Yf,!0);De=Zf;Le=bg;U=$f;Oe.push((b,c)=>{if(ag()){var d=h.canvas;Sf(d.clientWidth,d.clientHeight,b,c)}else Sf(b,c,b,c)});return 1},X:()=>0,ba:(a,b)=>{if(a=X(a)){var c=a.pf;a.pf=b;b=c}else b=null;return b},Y:(a,b)=>{a=X(a);if(!a)return null;var c=a.af;a.af=b;return c},_:(a,b)=>{if(a=X(a)){var c=a.ff;a.ff=b;b=c}else b=null;return b},da:(a,b)=>{if(a=X(a)){var c=
a.gf;a.gf=b;b=c}else b=null;return b},la:a=>{var b=pf;pf=a;return b},ca:(a,b)=>{if(a=X(a)){var c=a.sf;a.sf=b;b=c}else b=null;return b},$:(a,b)=>{if(a=X(a)){var c=a.yf;a.yf=b;b=c}else b=null;return b},Z:(a,b)=>{if(a=X(a)){var c=a.Bf;a.Bf=b;b=c}else b=null;return b},ea:(a,b)=>{a=X(a);if(!a)return null;var c=a.sg;a.sg=b;return c},fa:(a,b)=>{a=X(a);if(!a)return null;var c=a.tg;a.tg=b;return c},ne:(a,b)=>{if(a=X(a))a.Lg=b},ga:(a,b)=>{if(a=X(a)){var c=a.Cf;a.Cf=b;b=c}else b=null;return b},qa:()=>{},x:()=>
{window.removeEventListener("gamepadconnected",Bf,!0);window.removeEventListener("gamepaddisconnected",Cf,!0);window.removeEventListener("keydown",Df,!0);window.removeEventListener("keypress",xf,!0);window.removeEventListener("keyup",Ef,!0);window.removeEventListener("blur",Ff,!0);var a=h.canvas;a.removeEventListener("touchmove",Hf,!0);a.removeEventListener("touchstart",Of,!0);a.removeEventListener("touchcancel",Pf,!0);a.removeEventListener("touchend",Pf,!0);a.removeEventListener("mousemove",Hf,!0);
a.removeEventListener("mousedown",Of,!0);a.removeEventListener("mouseup",Pf,!0);a.removeEventListener("wheel",Qf,!0);a.removeEventListener("mousewheel",Qf,!0);a.removeEventListener("mouseenter",If,!0);a.removeEventListener("mouseleave",Jf,!0);a.removeEventListener("drop",Xf,!0);a.removeEventListener("dragover",Yf,!0);sf&&sf.removeEventListener("change",eg);a.width=a.height=1;Y=W=null},a:(a,b)=>{Ae[a]=b}},Hg;
(async function(){function a(c){var d=Hg=c.exports;c={};for(let [e,f]of Object.entries(d))"function"==typeof f?(d=hg(f),c[e]=d):c[e]=f;Hg=c;pa=Hg.te;ua();c=Hg;h._main=Fg=c.ve;h._malloc=R=c.we;Wf=c.xe;Cg=c.ye;Dg=c.ze;Eg=c.Ae;dynCall_vii=c.Be;Rf=c.Ce;yf=c.De;Mf=c.Ee;Gf=c.Fe;ie=c.He;dynCall_vi=c.Ie;dynCall_v=c.Pe;dynCall_iii=c.Re;fg=c.Ve;xg=c.lf;kg=c.mf;wg=c.nf;yg=c.of;ya("wasm-instantiate");return Hg}xa("wasm-instantiate");var b={a:Gg};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,
(d,e)=>{c(a(d,e))})});Aa??=h.locateFile?h.locateFile("RaylibTest.wasm",ia):ia+"RaylibTest.wasm";return a((await Da(b)).instance)})();
function Ig(){function a(){h.calledRun=!0;if(!m){if(!h.noFSInit&&!tb){var b,c;tb=!0;b??=h.stdin;c??=h.stdout;d??=h.stderr;b?Yb("/dev","stdin",b):Ob("/dev/tty","/dev/stdin");c?Yb("/dev","stdout",null,c):Ob("/dev/tty","/dev/stdout");d?Yb("/dev","stderr",null,d):Ob("/dev/tty1","/dev/stderr");Rb("/dev/stdin",0);Rb("/dev/stdout",1);Rb("/dev/stderr",1)}Hg.ue();ub=!1;h.onRuntimeInitialized?.();if(!h.noInitialRun){var d=Fg;try{var e=d(0,0);oa=e;qe(e)}catch(f){oe(f)}}if(h.postRun)for("function"==typeof h.postRun&&
(h.postRun=[h.postRun]);h.postRun.length;)e=h.postRun.shift(),Ga.push(e);Fa(Ga)}}if(0<va)wa=Ig;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ia();Fa(Ha);0<va?wa=Ig:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);a()},1)):a()}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();Ig();
